### ISSUE TITLE
Conflicting code snippet

### ISSUE THREAD

**Issue by zufre** [learn-co-curriculum/oo-custom-errors#19]
There seems to be conflicting information here: error class is in the Triangle class and not outside.

> This custom error class should be defined in the same file as the Triangle class, but outside of the class definition of Triangle. Like this:
> 
>       
>  
> class Triangle
>       ...triangle code
>  
>     class TriangleError < StandardError
>         ...triangle error code
>     end
> end

**Comment by sgharms** [comment]
@zufre I agree with your assessment! I don't see a reference to `Triangle`s in this lesson, though. Is there some other lesson that has this problem? If so, could you open your issue there? Or tell us where it is? 

I'm going to close this issue, because I think the solution should be on another but let me know if I missed something.

Steven
