### ISSUE TITLE
Says it's a code along, but only requires reading

### ISSUE THREAD

**Issue by regilfillan** [learn-co-curriculum/oo-custom-errors#20]
There's just the Sandbox environment, so if this was meant to be a code along like others in the past, just wanted to let you know.

**Comment by maxwellbenton** [comment]
Hi @regilfillan,

Thank you for spotting this and providing feedback. We've updated this lesson's structure so that it will behave as a code-along for students going forward.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
